name: run-tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate
        

      - name: Install pytest
        run: pip install pytest


      - name: Run tests
        run: pytest code/oblig2/tests.py -r w



